# Generated by Django 5.2.4 on 2025-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
