# Generated by Django 5.2.4 on 2025-07-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="Category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
