# Generated by Django 5.2.4 on 2025-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField()),
                ("lastname", models.CharField()),
                (
                    "profileImage",
                    models.ImageField(blank=True, null=True, upload_to="user_images/"),
                ),
                ("brandname", models.CharField()),
                ("mobile", models.BigIntegerField()),
                ("adress", models.CharField()),
                ("pincode", models.IntegerField()),
                ("city", models.CharField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
