# Generated by Django 5.2.4 on 2025-08-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_contactinfo_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="brandname",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="city",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="profileImage",
        ),
    ]
